language: java
before_install:
- sudo apt-get -y install jq
- java -Xmx32m -version
before_script:
- ls -lah
- google-chrome-stable --version
addons:
  chrome: stable
  apt:
    packages:
    - openjdk-8-jdk

env:
  global:
  - CHROME_PROPERTIES="chrome.properties"
  - WITH_PARAMS="-Ddriver=chrome -Dchrome.capabilities.path=$CHROME_PROPERTIES" #add -ntp when maven will be >=3.6.1 on travis
  - GROUP_ID="com.epam.jdi"
  - NOPO_TESTS="jdi-bdd-no-po-tests"
  - NOPO_TESTS_PROPERTY="test-examples/jdi-bdd-no-po-tests"
  - BDD_TESTS="jdi-bdd-tests"
  - BOOTSTRAP_TESTS="jdi-light-bootstrap-tests"
  - HTML_TESTS="jdi-light-html-tests"
  - ANGULAR_TESTS="jdi-light-angular-tests"
  - EXAMPLES="jdi-light-examples"
  - EXAMPLES_PROPERTY="test-examples/jdi-light-examples"
  - PERFORMANCE="jdi-performance"
  - PERFORMANCE_PROPERTY="test-examples/jdi-performance"
  - CHROME_ARGS="--headless"
  - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
  - PATH="$JAVA_HOME/bin:$PATH"

stages:
- prepare
- compile

jobs:
  include:
  - stage: prepare
    name: Welcome to jdi
    script:
    - echo ------------------- WELCOME TO JDI ----------------------
    - mvn --version #it is helpful

  - stage: compile
    name: Compile jdi code
    script:
    - mvn install -DskipTests

after_failure:
- echo "Build was failed"
after_success:
- echo "Build was successful"
# extra time during long builds
install:
- travis_wait
